# Generated by Django 4.2.6 on 2023-12-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fevbonus', models.IntegerField()),
                ('pbonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dname', models.CharField(max_length=100)),
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ename', models.CharField(max_length=100)),
                ('empno', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
                ('sal', models.IntegerField(primary_key=True, serialize=False)),
                ('deptno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
        migrations.CreateModel(
            name='salgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hisal', models.IntegerField()),
                ('losal', models.IntegerField()),
                ('sal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
